Feature/unsupported browser page
apptension/react-boilerplate pull request #11
Opened 2017-11-03 13:56 UTC by mkmieciak

2017-11-03 14:03 UTC, pziemkowski requested changes

2017-11-03 14:03 UTC, pziemkowski commented on app/utils/__tests__/detection.spec.js
> +      successCallback.should.have.been.called;
shouldn't you use expect from chai here?

2017-11-03 14:03 UTC, pziemkowski commented on app/utils/__tests__/detection.spec.js
> +      successCallback.should.not.have.been.called;
expect?

2017-11-03 14:03 UTC, pziemkowski commented on app/utils/detection.js
> +export default class Detection {
`Detection` is too broad. Can you name it differently? e.g. `UnsupportedBrowserDetection` ?

2017-11-03 14:03 UTC, pziemkowski commented on app/utils/detection.js
> +        switch (optionKey) {
Can you use an object instead of switch case?

Switch is less readable and "mistake prone".

2017-11-03 14:07 UTC, wojciech-panek commented on app/main.js
> +detector.check();
Z tego co pamiętam z projektów u9 to cały kod związany z wykrywaniem był w osobnym entry poincie, w którym było podbite wsparcie przez babela do starszych przeglądarek. Kwestia jest taka, że jak to jest w tym samym entry poincie webpacka i coś się wywali to ten unsupported page się nie wyświetli.

2017-11-06 09:53 UTC, wojciech-panek commented on app/support.js
> +require('es5-shim');
I think that shims should be required before Detection just in case

2017-11-06 09:55 UTC, wojciech-panek commented on app/support.js
> +    setTimeout(() => window.initApp());
`setTimeout(window.initApp)`

2017-11-06 09:58 UTC, wojciech-panek approved these changes

2017-11-06 12:51 UTC, mikeqcp approved these changes

2017-11-08 13:41 UTC, pziemkowski approved these changes

2017-11-08 13:41 UTC, merged