Feature/upgrade libraries
apptension/react-boilerplate pull request #2
Opened 2017-08-01 09:40 UTC by bigsergey

2017-08-12 11:16 UTC, mikeqcp commented
@bigsergey It fails on initial build now. You removed `SpritesmithPlugin` from `webpack.base.babel.js`, but you still import generated `*.scss` files in `main.scss` which results in trying to require unexisting files.

2017-08-16 07:37 UTC, bigsergey commented
@mikeqcp I removed SpritesmithPlugin by mistake. I have fixed it, please check if it works now.

2017-08-16 11:04 UTC, pziemkowski requested changes
Are you sure everything works in production version? IntlProvider is most likely blocking rendering of its children when URL changes, because no props have changed

2017-08-16 11:04 UTC, patrykziem commented on app/modules/maintainers/__tests__/maintainers.sagas.spec.js
> +import maintainersSaga, { } from '../maintainers.sagas';
Can you remove empty brackets?

2017-08-17 15:23 UTC, pziemkowski approved these changes

2017-08-17 15:30 UTC, merged